# Site settings
title: David Stroem
twitter_username: StroemDavid
name: David Stroem

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks: 
 - title: GitHub
   url: https://github.com/dstroem
 - title: StackOverflow
   url: https://stackoverflow.com/users/973080/dstroem 
 - title: LinkedIn
   url: https://www.linkedin.com/in/david-stroem/

#Any buzzword skills you want to include
skills:
 - C#
 - TDD
 - Specflow
 - ASP.NET
 - Owin
 - SQL
 

#Work experience is required
roles:
- title: Senior Engineer. Team Leader Web Services
  start:2009
  end: 2011
  employer:EDI-Soft AS
  description:
 
 

#Education is required
education:
 - level: Master of Science (M.Sc.)
   date: 1994
   subject: Informationtechnology
   school: University of Stavanger

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - robhinds/learning-neural-networks
 



#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
   <strong>TBD</strong>:
 
